baseurl: '/dban2'
permalink: pretty
title: 'Dban2 Enterprise'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home:
  limit_posts: 3

collections:
  pos:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "pos"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: "images"
    values:
      image: true

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
